### ISSUE TITLE
Fetch list of all registered users

### ISSUE THREAD

**Issue by nehasingh1491** [sopra-fs21-group-02/server#32]
Get the list of all registered users of the application from the database

## Estimate

2h

## User Story

This task belongs to user story #28

**Comment by bschne** [comment]
Also needed for story #5

**Comment by KseniaBel** [comment]
@nehasingh1491 , this task is related to user story that is not in the Milestone3. I implemented getAllUsers for the Map story already .

**Comment by bschne** [comment]
Done via #64 by @KseniaBel, closing this.
